server:
  internalPort: 3001
  externalPort: 3001
  runMode: debug
  timeZone: America/New_York
  Secret: 0ca0dc81-0971-4cd6-ba55-7da36991a334
  SessionTimeoutHours: 24
cat:
  stoppingStd: 0.33
  stoppingNumItems: 12
  minimumNumItems: 4