"""Generate a Python <-> Go parity fixture for the BCM package.

Fits sklearn IsotonicRegression on synthetic (subset_score, gold_score)
pairs that mimic the structure of the cat_optimalcontrol manuscript's
subset-bias data, then dumps:

    bcm_fixture.json   -- the BCM in the format consumed by Go LoadSet.
    bcm_predictions.json -- a list of {input, expected} probe points
                            generated by sklearn.predict, that the Go
                            Apply implementation must reproduce within
                            numerical tolerance.

Run:
    python generate_fixture.py
"""

import json
import os

import numpy as np
from sklearn.isotonic import IsotonicRegression

HERE = os.path.dirname(os.path.abspath(__file__))


def synthesize_pairs(rng, n=400, true_slope=0.6, location_bias=-0.2,
                    spread=0.4, x_lo=-3.0, x_hi=3.0):
    """Synthesize (subset, gold) pairs that look like our manuscript data:

    a roughly linear gold = slope*subset + bias, with heteroscedastic noise,
    so isotonic regression will pull out a monotone increasing fit.
    """
    x = rng.uniform(x_lo, x_hi, size=n)
    y = true_slope * x + location_bias + rng.normal(0.0, spread * (1 + 0.2 * np.abs(x)))
    return x, y


def fit_and_dump():
    rng = np.random.default_rng(42)
    cells = {}
    for J in (5, 10, 20):
        # Different J -> different bias regime.
        slope = 0.5 + 0.05 * J / 20
        loc = -0.3 + 0.02 * J
        x, y = synthesize_pairs(rng, n=300 + 50 * J, true_slope=slope,
                                location_bias=loc, spread=0.5)
        iso = IsotonicRegression(out_of_bounds="clip").fit(x, y)
        cells[J] = {
            "iso": iso,
            "x_thresholds": iso.X_thresholds_.tolist(),
            "y_thresholds": iso.y_thresholds_.tolist(),
        }

    fixture = {
        "scale": "synthetic",
        "maps": {
            str(J): {
                "subset_size": J,
                "x_thresholds": cells[J]["x_thresholds"],
                "y_thresholds": cells[J]["y_thresholds"],
            }
            for J in cells
        },
    }
    with open(os.path.join(HERE, "bcm_fixture.json"), "w") as f:
        json.dump(fixture, f, indent=2)

    # Probe points that exercise: interior, exact threshold, below-min, above-max.
    probe_xs = np.concatenate([
        np.linspace(-4.0, 4.0, 41),
        np.array([-100.0, -3.0, -2.999, 0.0, 2.999, 3.0, 100.0]),
    ])
    probes = {}
    for J, info in cells.items():
        preds = info["iso"].predict(probe_xs).tolist()
        probes[str(J)] = [
            {"input": float(x), "expected": float(y)}
            for x, y in zip(probe_xs.tolist(), preds)
        ]

    with open(os.path.join(HERE, "bcm_predictions.json"), "w") as f:
        json.dump(probes, f, indent=2)

    print(f"Wrote bcm_fixture.json (3 cells, J in {list(cells)})")
    print(f"Wrote bcm_predictions.json ({len(probe_xs)} probes per cell)")


if __name__ == "__main__":
    fit_and_dump()
